spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
server:
  port: 30000

alibaba:
  cloud:
    access-key: LTAI5tPBc1TZhni48VJmQQfw
    secret-key: mvEXHwgNg2picnjB6JIKOA0wsQT2S7
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com

